// Generated by gencpp from file object_sorting/SetTarget.msg
// DO NOT EDIT!


#ifndef OBJECT_SORTING_MESSAGE_SETTARGET_H
#define OBJECT_SORTING_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <object_sorting/SetTargetRequest.h>
#include <object_sorting/SetTargetResponse.h>


namespace object_sorting
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace object_sorting


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_sorting::SetTarget > {
  static const char* value()
  {
    return "15a6bbca6b7bdaa8c9ab1c07de00a6ac";
  }

  static const char* value(const ::object_sorting::SetTarget&) { return value(); }
};

template<>
struct DataType< ::object_sorting::SetTarget > {
  static const char* value()
  {
    return "object_sorting/SetTarget";
  }

  static const char* value(const ::object_sorting::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::object_sorting::SetTargetRequest> should match
// service_traits::MD5Sum< ::object_sorting::SetTarget >
template<>
struct MD5Sum< ::object_sorting::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_sorting::SetTarget >::value();
  }
  static const char* value(const ::object_sorting::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_sorting::SetTargetRequest> should match
// service_traits::DataType< ::object_sorting::SetTarget >
template<>
struct DataType< ::object_sorting::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::object_sorting::SetTarget >::value();
  }
  static const char* value(const ::object_sorting::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_sorting::SetTargetResponse> should match
// service_traits::MD5Sum< ::object_sorting::SetTarget >
template<>
struct MD5Sum< ::object_sorting::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_sorting::SetTarget >::value();
  }
  static const char* value(const ::object_sorting::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_sorting::SetTargetResponse> should match
// service_traits::DataType< ::object_sorting::SetTarget >
template<>
struct DataType< ::object_sorting::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::object_sorting::SetTarget >::value();
  }
  static const char* value(const ::object_sorting::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_SORTING_MESSAGE_SETTARGET_H
