// Generated by gencpp from file warehouse/Pose.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MESSAGE_POSE_H
#define WAREHOUSE_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <warehouse/Rotate.h>

namespace warehouse
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : position()
    , rotation()  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , rotation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::warehouse::Rotate_<ContainerAllocator>  _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::warehouse::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::warehouse::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::warehouse::Pose > PosePtr;
typedef boost::shared_ptr< ::warehouse::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse::Pose_<ContainerAllocator1> & lhs, const ::warehouse::Pose_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.rotation == rhs.rotation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse::Pose_<ContainerAllocator1> & lhs, const ::warehouse::Pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::warehouse::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e48a5367d8266f8aaac3d6b58f5cb2";
  }

  static const char* value(const ::warehouse::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e48a5367d8266fULL;
  static const uint64_t static_value2 = 0x8aaac3d6b58f5cb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse/Pose";
  }

  static const char* value(const ::warehouse::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"warehouse/Rotate rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: warehouse/Rotate\n"
"float64 r\n"
"float64 p\n"
"float64 y\n"
;
  }

  static const char* value(const ::warehouse::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse::Pose_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "rotation: ";
    s << std::endl;
    Printer< ::warehouse::Rotate_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_MESSAGE_POSE_H
