// Generated by gencpp from file warehouse/Rotate.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MESSAGE_ROTATE_H
#define WAREHOUSE_MESSAGE_ROTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehouse
{
template <class ContainerAllocator>
struct Rotate_
{
  typedef Rotate_<ContainerAllocator> Type;

  Rotate_()
    : r(0.0)
    , p(0.0)
    , y(0.0)  {
    }
  Rotate_(const ContainerAllocator& _alloc)
    : r(0.0)
    , p(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _r_type;
  _r_type r;

   typedef double _p_type;
  _p_type p;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::warehouse::Rotate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehouse::Rotate_<ContainerAllocator> const> ConstPtr;

}; // struct Rotate_

typedef ::warehouse::Rotate_<std::allocator<void> > Rotate;

typedef boost::shared_ptr< ::warehouse::Rotate > RotatePtr;
typedef boost::shared_ptr< ::warehouse::Rotate const> RotateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehouse::Rotate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehouse::Rotate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehouse::Rotate_<ContainerAllocator1> & lhs, const ::warehouse::Rotate_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r &&
    lhs.p == rhs.p &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehouse::Rotate_<ContainerAllocator1> & lhs, const ::warehouse::Rotate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehouse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::warehouse::Rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehouse::Rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse::Rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehouse::Rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse::Rotate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehouse::Rotate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehouse::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5585e6b09b13f56ed964334fed50470";
  }

  static const char* value(const ::warehouse::Rotate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5585e6b09b13f56ULL;
  static const uint64_t static_value2 = 0xed964334fed50470ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehouse::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehouse/Rotate";
  }

  static const char* value(const ::warehouse::Rotate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehouse::Rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 r\n"
"float64 p\n"
"float64 y\n"
;
  }

  static const char* value(const ::warehouse::Rotate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehouse::Rotate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.p);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rotate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehouse::Rotate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehouse::Rotate_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "p: ";
    Printer<double>::stream(s, indent + "  ", v.p);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSE_MESSAGE_ROTATE_H
