// Generated by gencpp from file warehouse/SetExchangeTarget.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MESSAGE_SETEXCHANGETARGET_H
#define WAREHOUSE_MESSAGE_SETEXCHANGETARGET_H

#include <ros/service_traits.h>


#include <warehouse/SetExchangeTargetRequest.h>
#include <warehouse/SetExchangeTargetResponse.h>


namespace warehouse
{

struct SetExchangeTarget
{

typedef SetExchangeTargetRequest Request;
typedef SetExchangeTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetExchangeTarget
} // namespace warehouse


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehouse::SetExchangeTarget > {
  static const char* value()
  {
    return "73a1985add1021f1387d4b37533c9d6c";
  }

  static const char* value(const ::warehouse::SetExchangeTarget&) { return value(); }
};

template<>
struct DataType< ::warehouse::SetExchangeTarget > {
  static const char* value()
  {
    return "warehouse/SetExchangeTarget";
  }

  static const char* value(const ::warehouse::SetExchangeTarget&) { return value(); }
};


// service_traits::MD5Sum< ::warehouse::SetExchangeTargetRequest> should match
// service_traits::MD5Sum< ::warehouse::SetExchangeTarget >
template<>
struct MD5Sum< ::warehouse::SetExchangeTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse::SetExchangeTarget >::value();
  }
  static const char* value(const ::warehouse::SetExchangeTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse::SetExchangeTargetRequest> should match
// service_traits::DataType< ::warehouse::SetExchangeTarget >
template<>
struct DataType< ::warehouse::SetExchangeTargetRequest>
{
  static const char* value()
  {
    return DataType< ::warehouse::SetExchangeTarget >::value();
  }
  static const char* value(const ::warehouse::SetExchangeTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehouse::SetExchangeTargetResponse> should match
// service_traits::MD5Sum< ::warehouse::SetExchangeTarget >
template<>
struct MD5Sum< ::warehouse::SetExchangeTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse::SetExchangeTarget >::value();
  }
  static const char* value(const ::warehouse::SetExchangeTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse::SetExchangeTargetResponse> should match
// service_traits::DataType< ::warehouse::SetExchangeTarget >
template<>
struct DataType< ::warehouse::SetExchangeTargetResponse>
{
  static const char* value()
  {
    return DataType< ::warehouse::SetExchangeTarget >::value();
  }
  static const char* value(const ::warehouse::SetExchangeTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSE_MESSAGE_SETEXCHANGETARGET_H
