// Generated by gencpp from file warehouse/SetInTarget.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MESSAGE_SETINTARGET_H
#define WAREHOUSE_MESSAGE_SETINTARGET_H

#include <ros/service_traits.h>


#include <warehouse/SetInTargetRequest.h>
#include <warehouse/SetInTargetResponse.h>


namespace warehouse
{

struct SetInTarget
{

typedef SetInTargetRequest Request;
typedef SetInTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInTarget
} // namespace warehouse


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehouse::SetInTarget > {
  static const char* value()
  {
    return "3a5188a131c4178e5804bbb1ba83e677";
  }

  static const char* value(const ::warehouse::SetInTarget&) { return value(); }
};

template<>
struct DataType< ::warehouse::SetInTarget > {
  static const char* value()
  {
    return "warehouse/SetInTarget";
  }

  static const char* value(const ::warehouse::SetInTarget&) { return value(); }
};


// service_traits::MD5Sum< ::warehouse::SetInTargetRequest> should match
// service_traits::MD5Sum< ::warehouse::SetInTarget >
template<>
struct MD5Sum< ::warehouse::SetInTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse::SetInTarget >::value();
  }
  static const char* value(const ::warehouse::SetInTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse::SetInTargetRequest> should match
// service_traits::DataType< ::warehouse::SetInTarget >
template<>
struct DataType< ::warehouse::SetInTargetRequest>
{
  static const char* value()
  {
    return DataType< ::warehouse::SetInTarget >::value();
  }
  static const char* value(const ::warehouse::SetInTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehouse::SetInTargetResponse> should match
// service_traits::MD5Sum< ::warehouse::SetInTarget >
template<>
struct MD5Sum< ::warehouse::SetInTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse::SetInTarget >::value();
  }
  static const char* value(const ::warehouse::SetInTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse::SetInTargetResponse> should match
// service_traits::DataType< ::warehouse::SetInTarget >
template<>
struct DataType< ::warehouse::SetInTargetResponse>
{
  static const char* value()
  {
    return DataType< ::warehouse::SetInTarget >::value();
  }
  static const char* value(const ::warehouse::SetInTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSE_MESSAGE_SETINTARGET_H
