// Generated by gencpp from file warehouse/SetOutTarget.msg
// DO NOT EDIT!


#ifndef WAREHOUSE_MESSAGE_SETOUTTARGET_H
#define WAREHOUSE_MESSAGE_SETOUTTARGET_H

#include <ros/service_traits.h>


#include <warehouse/SetOutTargetRequest.h>
#include <warehouse/SetOutTargetResponse.h>


namespace warehouse
{

struct SetOutTarget
{

typedef SetOutTargetRequest Request;
typedef SetOutTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOutTarget
} // namespace warehouse


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehouse::SetOutTarget > {
  static const char* value()
  {
    return "73a1985add1021f1387d4b37533c9d6c";
  }

  static const char* value(const ::warehouse::SetOutTarget&) { return value(); }
};

template<>
struct DataType< ::warehouse::SetOutTarget > {
  static const char* value()
  {
    return "warehouse/SetOutTarget";
  }

  static const char* value(const ::warehouse::SetOutTarget&) { return value(); }
};


// service_traits::MD5Sum< ::warehouse::SetOutTargetRequest> should match
// service_traits::MD5Sum< ::warehouse::SetOutTarget >
template<>
struct MD5Sum< ::warehouse::SetOutTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse::SetOutTarget >::value();
  }
  static const char* value(const ::warehouse::SetOutTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse::SetOutTargetRequest> should match
// service_traits::DataType< ::warehouse::SetOutTarget >
template<>
struct DataType< ::warehouse::SetOutTargetRequest>
{
  static const char* value()
  {
    return DataType< ::warehouse::SetOutTarget >::value();
  }
  static const char* value(const ::warehouse::SetOutTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehouse::SetOutTargetResponse> should match
// service_traits::MD5Sum< ::warehouse::SetOutTarget >
template<>
struct MD5Sum< ::warehouse::SetOutTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehouse::SetOutTarget >::value();
  }
  static const char* value(const ::warehouse::SetOutTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehouse::SetOutTargetResponse> should match
// service_traits::DataType< ::warehouse::SetOutTarget >
template<>
struct DataType< ::warehouse::SetOutTargetResponse>
{
  static const char* value()
  {
    return DataType< ::warehouse::SetOutTarget >::value();
  }
  static const char* value(const ::warehouse::SetOutTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSE_MESSAGE_SETOUTTARGET_H
