// Generated by gencpp from file object_pallezting/SetTargetRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_PALLEZTING_MESSAGE_SETTARGETREQUEST_H
#define OBJECT_PALLEZTING_MESSAGE_SETTARGETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_pallezting
{
template <class ContainerAllocator>
struct SetTargetRequest_
{
  typedef SetTargetRequest_<ContainerAllocator> Type;

  SetTargetRequest_()
    : color()
    , tag()  {
    }
  SetTargetRequest_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , tag(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _color_type;
  _color_type color;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _tag_type;
  _tag_type tag;





  typedef boost::shared_ptr< ::object_pallezting::SetTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_pallezting::SetTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetRequest_

typedef ::object_pallezting::SetTargetRequest_<std::allocator<void> > SetTargetRequest;

typedef boost::shared_ptr< ::object_pallezting::SetTargetRequest > SetTargetRequestPtr;
typedef boost::shared_ptr< ::object_pallezting::SetTargetRequest const> SetTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_pallezting::SetTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_pallezting::SetTargetRequest_<ContainerAllocator1> & lhs, const ::object_pallezting::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.tag == rhs.tag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_pallezting::SetTargetRequest_<ContainerAllocator1> & lhs, const ::object_pallezting::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_pallezting

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_pallezting::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_pallezting::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_pallezting::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d56a5dd57cf3ca58e9236294da9e9e4";
  }

  static const char* value(const ::object_pallezting::SetTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d56a5dd57cf3ca5ULL;
  static const uint64_t static_value2 = 0x8e9236294da9e9e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_pallezting/SetTargetRequest";
  }

  static const char* value(const ::object_pallezting::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] color\n"
"string[] tag\n"
;
  }

  static const char* value(const ::object_pallezting::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.tag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_pallezting::SetTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_pallezting::SetTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color[i]);
    }
    s << indent << "tag[]" << std::endl;
    for (size_t i = 0; i < v.tag.size(); ++i)
    {
      s << indent << "  tag[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tag[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_PALLEZTING_MESSAGE_SETTARGETREQUEST_H
