(cl:defpackage warehouse-srv
  (:use )
  (:export
   "SETEXCHANGETARGET"
   "<SETEXCHANGETARGET-REQUEST>"
   "SETEXCHANGETARGET-REQUEST"
   "<SETEXCHANGETARGET-RESPONSE>"
   "SETEXCHANGETARGET-RESPONSE"
   "SETINTARGET"
   "<SETINTARGET-REQUEST>"
   "SETINTARGET-REQUEST"
   "<SETINTARGET-RESPONSE>"
   "SETINTARGET-RESPONSE"
   "SETOUTTARGET"
   "<SETOUTTARGET-REQUEST>"
   "SETOUTTARGET-REQUEST"
   "<SETOUTTARGET-RESPONSE>"
   "SETOUTTARGET-RESPONSE"
  ))

